Fix compile warning: conflicting types for built-in function ‘log2’
Actual warning:

qsutil.h:5: warning: conflicting types for built-in function ‘log2’

Just a rename from log2() to log_2() resolves this warning.

grep log2 output from qmail source as below:

grep log2 ./*
./qmail-send.c:   log2("bounce msg ",strnum2);
./qmail-send.c:    log2(chanstatusmsg[c],strnum2);
./qmail-send.c:    log2("/",strnum3);
./qmail-send.c: log2("starting delivery ",strnum2);
./qmail-send.c:       log2("info msg ",strnum3);
./qmail-send.c:       log2(": bytes ",strnum2);
./qmail-send.c:       log2("> qp ",strnum2);
./qmail-send.c:       log2(" uid ",strnum2);
./qsutil.c:void log2(s1,s2) char *s1; char *s2; {
./qsutil.h:extern void log2();

So we change log2() to log_2() of all the mentioned files as stated above.

Signed-off-by: Giam Teck Choon <giamteckchoon@gmail.com>