Rename void puts(s) to void outs(s)
Fix the following compile warnings:

auto-str.c:8: warning: conflicting types for built-in function ‘puts’
auto-int8.c:10: warning: conflicting types for built-in function ‘puts’
auto-int.c:10: warning: conflicting types for built-in function ‘puts’
qmail-inject.c:58: warning: conflicting types for built-in function ‘puts’
qmail-pop3d.c:48: warning: conflicting types for built-in function ‘puts’
qmail-popup.c:41: warning: conflicting types for built-in function ‘puts’

One such situation happened in auto-uid.c as commented below:

auto-uid.c:void outs(s) /* was named puts, but Solaris pwd.h includes stdio.h. dorks. */

So we change all of the following source files to reflect such instead:

auto-int8.c
auto-int.c
auto-str.c
qmail-inject.c
qmail-pop3d.c
qmail-popup.c

Signed-off-by: Giam Teck Choon <giamteckchoon@gmail.com>